spring:
  application:
    name: tara-login-service
    instance-id: ${APP_INSTANCE_ID:${random.int(100)}}
  session:
    timeout: 300s
    servlet:
      # SessionRepositoryFilter should be invoked before other filters so, that
      # Spring Session backed HttpSession implementation is available to subsequent filters.
      filter-order: -2147483648

management:
  health:
    defaults:
      enabled: false
  info:
    git:
      mode: full
  endpoints:
    web:
      base-path: /
      exposure:
        exclude: "*"
    jmx:
      exposure:
        exclude: "*"

ignite:
  ignite-instance-name: tara-ignite
  metrics-log-frequency: 300000
