package ee.ria.taraauthserver.session;

public enum AuthState {
    INIT_AUTH_PROCESS,
    AUTHENTICATION_SUCCESS,
    INIT_MID,
    POLL_MID_STATUS,
    COMPLETE,
    NATURAL_PERSON_AUTHENTICATION_COMPLETED,
    AUTHENTICATION_FAILED,
    LEGAL_PERSON_AUTHENTICATION_INIT,
    GET_LEGAL_PERSON_LIST,
    LEGAL_PERSON_AUTHENTICATION_COMPLETED;
}