package ee.ria.taraauthserver.session;

public enum TaraAuthenticationState {
    NOT_SET,
    INIT_AUTH_PROCESS,
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_CANCELED,
    AUTHENTICATION_FAILED,
    INIT_MID,
    @Deprecated INIT_SID, // Unused, left for backwards compatibility in Ignite
    INIT_SID_WEB2APP,
    INIT_SID_QR_CODE,
    POLL_MID_STATUS,
    POLL_MID_STATUS_CANCELED,
    @Deprecated POLL_SID_STATUS, // Unused, left for backwards compatibility in Ignite
    POLL_SID_WEB2APP_STATUS,
    POLL_SID_WEB2APP_STATUS_AFTER_FINAL_STATUS_RECEIVED,
    POLL_SID_QR_CODE,
    POLL_SID_STATUS_CANCELED,
    COMPLETE,
    NATURAL_PERSON_AUTHENTICATION_COMPLETED,
    LEGAL_PERSON_AUTHENTICATION_INIT,
    GET_LEGAL_PERSON_LIST,
    LEGAL_PERSON_AUTHENTICATION_COMPLETED,
    NATURAL_PERSON_AUTHENTICATION_CHECK_ESTEID_CERT,
    CONSENT_NOT_REQUIRED,
    INIT_CONSENT_PROCESS,
    CONSENT_GIVEN,
    CONSENT_NOT_GIVEN,
    WAITING_EIDAS_RESPONSE,
    EXTERNAL_TRANSACTION
}
